language: php

php:
  - 7.2.5
  - 7.1.9

matrix:
  allow_failures:
    - php: 7.1.9

install:
  - composer install

cache:
  directories:
  - vendor

script:
  - composer dump -o
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
  - composer require php-coveralls/php-coveralls
  - travis_retry php vendor/bin/php-coveralls